apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      containers:
      - name: auth-backend
        image: aiyzajunaid/auth-backend:latest
        ports:
        - containerPort: 3145
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/ClassroomMS"
